
POST http://localhost:8788/api/eta
Content-Type: application/json

[
    {
        "company": "kmb",
        "routeType": "1",
        "routeId": "1",
        "stop": "C88E34E485B43EFB",
        "dir": "O"
    },
    {
        "company": "ctb",
        "routeId": "1",
        "stop": "002403",
        "dir": "I"
    },
    {
        "company": "nlb",
        "routeId": "1",
        "stop": "1"
    },
    {
        "company": "gmb",
        "routeId": "2002337",
        "routeType": "1",
        "stop": "20001113"
    },
    {
        "company": "mtr",
        "routeId": "506",
        "stop": "506-U020"
    },
    {
        "company": "mtr_hr",
        "routeId": "TML",
        "dir": "DT",
        "stop": "HIK"
    },
    {
        "company": "mtr_lr",
        "routeId": "505",
        "dir": "2",
        "stop": "120"
    }
]