name: Test
on:
  workflow_dispatch:
  push:
    paths:
      - 'functions/**'
jobs:
  update:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node env
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install

      - name: Run test
        run: |
          echo "FORCE_COLOR=true" >> $GITHUB_ENV
          npm run send-tg-noti
        env:
          TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID }}
