name: Test Cloudflare Functions
on:
  workflow_dispatch:
  push:
    paths:
      - 'functions/**'
jobs:
  update:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Load cache - stop data
        uses: actions/cache/restore@v6
        with:
          path: cache
          key: stop-data-20260929-2
          restore-keys: stop-data

      - name: Copy file
        run: |
          cp gmb_stop_20023329.json cache/gmb_stop_20023329.json
          cp gmb_stop_20023330.json cache/gmb_stop_20023330.json
          cp gmb_stop_20023331.json cache/gmb_stop_20023331.json
          cp gmb_stop_20023332.json cache/gmb_stop_20023332.json
          cp gmb_stop_20023333.json cache/gmb_stop_20023333.json
          cp gmb_stop_20023334.json cache/gmb_stop_20023334.json
          cp gmb_stop_20023362.json cache/gmb_stop_20023362.json
          cp gmb_stop_20023395.json cache/gmb_stop_20023395.json

      - name: Update Cache
        uses: actions/cache/save@v6
        with:
          path: cache
          key: stop-data-20260929-3
