name: Update Spatial Data
on:
  workflow_dispatch:
    inputs:
      forceUpdate:
        description: 'Force update'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 9 * * *'
jobs:
  update:
    name: Update Spatial Data
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=8192"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node env
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install osmium-tool
        run: sudo apt install -y osmium-tool jq curl

      - name: Extract geojson from osm
        working-directory: ./osm
        shell: bash
        run: |
          curl -L -o hk.osm.pbf https://download.geofabrik.de/asia/china/hong-kong-latest.osm.pbf
          osmium fileinfo hk.osm.pbf
          chmod +x ./extract_relation.sh
          ./extract_relation.sh hk.osm.pbf

      - name: Install dependencies
        run: |
          npm install

      - name: Update Spatial Data
        run: |
          npm run update-spatial
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID }}
          FORCE_UPDATE: ${{ inputs.forceUpdate || 'false' }}

      - name: Commit and Push data
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update Spatial data
          file_pattern: 'public/api/spatial/**'
          #commit_author: kennyfong19931 <kennyfong19931@users.noreply.github.com>

      - name: Send Telegram Notification
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: npm run send-tg-noti
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ vars.TELEGRAM_TOPIC_ID }}
