name: Update Route Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'
jobs:
  update:
    name: Update Route Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node env
        uses: actions/setup-node@v7
        with:
          node-version: 24

      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Load cache - stop data
        uses: actions/cache/restore@v6
        with:
          path: cache
          key: stop-data-${{ steps.get-date.outputs.date }}
          restore-keys: stop-data

      - name: Load cache - gtfs data
        uses: actions/cache/restore@v6
        with:
          path: gtfs
          key: gtfs-data-${{ steps.get-date.outputs.date }}
          restore-keys: gtfs-data

      - name: Install dependencies
        run: |
          npm install

      - name: Update Route Data
        run: |
          npm run update-route

      - name: Merge Route Data with GTFS
        run: |
          npm run merge-route

      - name: Generate sitemap
        run: |
          npm run generate-sitemap

      - name: Commit and Push data
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update Route data
          file_pattern: 'public/api/route/**'
          #commit_author: Actions <github-actions[bot]@users.noreply.github.com>

      - name: Send Telegram Notification
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: npm run send-tg-noti
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
          GITHUB_RUN_ID: $GITHUB_RUN_ID

      - name: Cache GMB Route data
        if: always() && !cancelled() && env.updateCache == 'true'
        uses: actions/cache/save@v6
        with:
          path: cache
          key: stop-data-${{ steps.get-date.outputs.date }}

      - name: Update Stop Name on exception
        if: failure() && env.runUpdateStopName == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run updateStopName.yml -f reRunId=$GITHUB_RUN_ID
